# Generated by Django 2.0.1 on 2018-01-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
                ('executionTime', models.CharField(max_length=10)),
                ('testCase', models.CharField(max_length=250)),
            ],
        ),
    ]
