# Generated by Django 2.0.1 on 2018-01-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcasename', models.CharField(help_text='Please enter testcase name', max_length=200, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('executiontime', models.CharField(max_length=10)),
                ('testcase', models.CharField(max_length=250)),
                ('log_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Please enter testsuite name', max_length=250)),
                ('testcasetitle', models.CharField(help_text='Please enter testcase title', max_length=250)),
                ('modulepathclassname', models.CharField(help_text='Please enter module path and space with class name ', max_length=250)),
                ('description', models.TextField(help_text='Please enter description of testsuite', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='test_result',
        ),
        migrations.AddField(
            model_name='testresult',
            name='testsuiteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.TestSuite'),
        ),
    ]
