# Generated by Django 2.0.1 on 2018-01-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180123_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Please enter device name', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='', help_text='Please enter platform name', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='log_path',
            new_name='log_file_path',
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='category',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='modulepathclassname',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='testsuiteid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='first_app.TestSuite'),
        ),
        migrations.AddField(
            model_name='dutcategory',
            name='platform_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='first_app.Platform'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='categoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='first_app.DutCategory'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='platformid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='first_app.Platform'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='first_app.DutCategory'),
        ),
    ]
