# Generated by Django 2.0.1 on 2018-01-28 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180125_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsuite',
            old_name='category_id',
            new_name='category',
        ),
    ]
