# Generated by Django 2.0.1 on 2018-01-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20180128_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='sub_category',
        ),
    ]
